# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "miyan's blog"
weight = 1
[zh-cn]
languageName = "中文"
languagedirection = "ltr"
title = "miyan的博客"
weight = 1