# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/miyanyan"

[social.params]
icon = "github"

[[social]]
identifier = "zhihu"
name = "Zhihu"
url = "https://www.zhihu.com/people/li-xiao-yan-98-60"

[social.params]
icon = "zhihu"

[[social]]
identifier = "leetcode"
name = "Leetcode"
url = "https://leetcode.cn/u/miyanyanyan/"

[social.params]
icon = "leetcode"
